### ISSUE TITLE
high chart is not visible

### ISSUE THREAD

**Issue by ajkosh** [miloschuman/yii2-highcharts#50] opened 2016-12-09 11:13 UTC
when i m using any chart it is showing black color box,no chart.
![erorrr](https://cloud.githubusercontent.com/assets/8582472/21047195/9162aece-be2e-11e6-8a59-cfb15750b0a3.png)

**Comment by miloschuman** [comment] 2016-12-13 20:21
@ajkosh, I am unable to reproduce. Do you have a public facing page or fiddle to test?

**Comment by dantux** [comment] 2017-01-31 00:15
I have a similar issue. Regardless what options I choose for the chart (I tried copying the example chart in your github readme) and it doesn't show anything.
Firefox in the web developer toolbar shows these errors:

`Use of Mutation Events is deprecated. Use MutationObserver instead.  ContentVeil.js:2:4726
TypeError: can't assign to properties of (new String("{ \"color\": \"#333333\", \"fontSize\": \"18px\" }")): not an object`

Any ideas?

**Comment by miloschuman** [comment] 2017-01-31 22:01
@dantux, that first error appears to be from a script included via an Evernote browser extension and is unrelated. The second error should lead you to the likely culprit in your code. Search your highcharts widget code for a string like `{ "color": "#333333", "fontSize": "18px" }`. If you need to pass any JavaScript/JSON options, they must be wrapped in a `new JsExpression()` object or else they'll be interpreted as a string. For instance, instead of
```php
'someOption' => "{ \"color\": \"#333333\", \"fontSize\": \"18px\" }",
```
... use
```php
'someOption' => new JSExpression("{ \"color\": \"#333333\", \"fontSize\": \"18px\" }"),
```

**Closed by miloschuman** 2017-01-31 22:01 UTC
